language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
jobs:
  include:
  - stage: Continuous Integration
    script:
    - dotnet build -c Release
    - dotnet test ./Ioannis.ETLWorkflows.SDK.Tests/
    - dotnet test ./Ioannis.ETLWorkflows.Core.Tests/