language: csharp
solution: ETLWorkflows.sln
dotnet: 2.2
install:
  - nuget restore ETLWorkflows.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ETLWorkflows.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./ETLWorkflows.SDK.Tests/bin/Release/ETLWorkflows.SDK.Tests.dll